language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install: pip install tox-travis tox flake8
dist: xenial
services:
  - postgresql
sudo: false
script: tox
before_script:
  - flake8 django_migration_testcase tests --ignore=E501,E128,E402
  - psql -c 'create database migration_test;' -U postgres
